apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: write-timestamp-job
  annotations:
    argocd.argoproj.io/sync-options: Force=true, Delete=false
spec:
  template:
    spec:
      containers:
      - name: write-timestamp
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Execution Timestamp: $TIMESTAMP" >> /data/sync.txt
          echo "Content of /data/sync.txt:"
          cat /data/sync.txt
        volumeMounts:
        - mountPath: /data
          name: data-volume
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
  backoffLimit: 4
